/**
 * Demonstrates sb.exec(cmd, { interactive: true }):
 *   Open a live, bidirectional PTY session inside an Ubuntu sandbox, drive it
 *   like a human would (export a var, create a file), checkpoint mid-session,
 *   then resume — proving the recorded stdin is replayed for real against the
 *   freshly restored filesystem, reconstructing shell state rather than just
 *   the audit trail.
 *
 * Verification uses a single atomic diagnostic command rather than separate
 * write()s with substring checks. A real PTY echoes typed input back and its
 * timing relative to actual command output isn't guaranteed line-by-line over
 * a proxied connection — but everything one `echo "...$(cmd)..."` invocation
 * produces is generated by bash as a single piece of output, so it can't be
 * split or reordered by transport-level interleaving the way separate
 * commands and their echoes can.
 */
import { Drej } from "drej";
import { SQLiteAdapter } from "@drej/sqlite";

function assertEqual(actual: string, expected: string, label: string) {
  if (actual !== expected) {
    throw new Error(
      `FAILED: ${label}\n  expected: ${JSON.stringify(expected)}\n  actual:   ${JSON.stringify(actual)}`,
    );
  }
  console.log(`  ok — ${label}`);
}

const client = new Drej({
  baseUrl: process.env.OPEN_SANDBOX_URL ?? "http://127.0.0.1:8080",
  apiKey: process.env.OPEN_SANDBOX_API_KEY ?? "",
  adapter: new SQLiteAdapter("./ledger.db"),
  useServerProxy: process.env.USE_SERVER_PROXY !== "false",
});

const sb = await client.sandbox({
  image: "ubuntu:22.04",
  resources: { cpu: "500m", memory: "512Mi" },
  name: "interactive-exec-demo",
});

let resumed: Awaited<ReturnType<typeof client.resume>> | undefined;

try {
  console.log(`Sandbox ID: ${sb.sandboxId}`);
  console.log("\n=== Opening an interactive bash session ===\n");

  const shell = sb.exec("bash", { interactive: true });

  // Drive it like a human would — no single command carries all of this state.
  shell.write("export SECRET=42\n");
  shell.write("mkdir -p /tmp/work && cd /tmp/work\n");
  shell.write("echo state-before-checkpoint > marker.txt\n");
  shell.write("echo setup-done\n");

  // Give the shell a moment to actually run the setup before snapshotting it.
  await new Promise((r) => setTimeout(r, 1500));

  console.log("\n=== Checkpointing while the shell is still open ===\n");
  await sb.checkpoint("mid-session");

  console.log("\n=== Resuming from that checkpoint ===\n");
  resumed = await client.resume(sb.sandboxId);
  console.log(`Resumed sandbox ID: ${resumed.sandboxId}`);

  // Same call site, same program order -> same seq -> the resume path picks up
  // the still-open interactive session and replays its recorded stdin for real
  // against the freshly restored filesystem before handing control back live.
  const shell2 = resumed.exec("bash", { interactive: true });
  void shell2.pipe({ write: (chunk: string) => process.stdout.write(`[resumed] ${chunk}`) });

  // One atomic command — bash substitutes $(pwd)/$(cat ...)/$SECRET itself and
  // emits the fully-resolved string as a single piece of output.
  shell2.write('echo "DIAG_START:$(pwd)|$(cat marker.txt 2>&1)|$SECRET:DIAG_END"\n');
  await new Promise((r) => setTimeout(r, 1000));
  shell2.write("exit\n");

  const result = await shell2; // resolves independently of the pipe() consumer above

  console.log("\n=== Verifying reconstructed shell state ===\n");
  const match = result.stdout.match(/DIAG_START:(.*?):DIAG_END/s);
  if (!match) {
    throw new Error(`FAILED: diagnostic marker not found in output:\n${result.stdout}`);
  }
  const [pwdVal, fileVal, secretVal] = match[1].split("|").map((s) => s.replace(/\r/g, "").trim());

  assertEqual(
    pwdVal,
    "/tmp/work",
    "cd /tmp/work survived resume (replayed against restored filesystem)",
  );
  assertEqual(
    fileVal,
    "state-before-checkpoint",
    "marker.txt written before checkpoint is present after resume",
  );
  assertEqual(
    secretVal,
    "42",
    "export SECRET=42 was re-derived by replaying stdin into the fresh shell",
  );

  if (result.exitCode !== 0) throw new Error(`expected exit code 0, got ${result.exitCode}`);
  console.log(`  ok — interactive exec resolved with exit code ${result.exitCode}`);

  console.log("\nAll assertions passed.");
} finally {
  await sb.close();
  await resumed?.close();
}
